#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:~/programmer/apache-maven-3.6.0/bin/:

alias sublime='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export JAVA_HOME="/opt/homebrew/opt/openjdk/"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/toreklevenberg/programmer/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/toreklevenberg/programmer/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/toreklevenberg/programmer/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/toreklevenberg/programmer/google-cloud-sdk/completion.zsh.inc'; fi
